name: Set up GAR (Google Artifact Registry) NPM config
description: Set up NPM config to publish/pull package from GCP with Workload Identity Provider on private repository

inputs:
  project-id:
    description: GCP project Id
    required: true
  region:
    description: region
    required: true
  repository-name:
    description: Google Artifact Registry name
    required: true
  service-account:
    description: GCP service account
    required: true
  scope:
    description: scope package name
    required: true
  workload-identity-provider:
    description: Identity Provider
    required: true

runs:
  using: composite
  steps:
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v0"
      with:
        create_credentials_file: false
        service_account: ${{ inputs.service-account }}
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.workload-identity-provider }}

    - name: Create .npmrc
      shell: bash
      run: |
        cat << EOF > .npmrc
          @${{ inputs.scope }}:registry=https://${{ inputs.region }}-npm.pkg.dev/${{ inputs.project-id }}/${{ inputs.repository-name }}/
          //${{ inputs.region }}-npm.pkg.dev/${{ inputs.project-id }}/${{ inputs.repository-name }}/:_authToken="${{ steps.auth.outputs.access_token }}"
          //${{ inputs.region }}-npm.pkg.dev/${{ inputs.project-id }}/${{ inputs.repository-name }}/:always-auth=true
        EOF
